-- MySQL Script generated by MySQL Workbench
-- Fri Feb  7 18:34:28 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mensakas
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mensakas
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mensakas` DEFAULT CHARACTER SET utf8 ;
USE `mensakas` ;

-- -----------------------------------------------------
-- Table `mensakas`.`business`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mensakas`.`business` (
  `business_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `phone` INT NOT NULL,
  `mail` VARCHAR(100) NOT NULL,
  `adress` VARCHAR(150) NOT NULL,
  `zip_code` INT(5) NOT NULL,
  `status` TINYINT NOT NULL,
  `lat` DECIMAL(14,8) NOT NULL,
  `lon` DECIMAL(14,8) NOT NULL,
  PRIMARY KEY (`business_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mensakas`.`mensaka`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mensakas`.`mensaka` (
  `mensakas_id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(100) NOT NULL,
  `status` TINYINT NOT NULL,
  `phone` INT(9) NOT NULL,
  PRIMARY KEY (`mensakas_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mensakas`.`users`
-- -----------------------------------------------------
-- CREATE TABLE IF NOT EXISTS `mensakas`.`users` (
--   `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
--   `name` VARCHAR(191) NOT NULL,
--   `email` VARCHAR(191) NOT NULL,
--   `email_verified_at` TIMESTAMP NULL DEFAULT NULL,
--   `password` VARCHAR(191) NOT NULL,
--   `remember_toke` VARCHAR(100) NULL DEFAULT NULL,
--   `created_at` TIMESTAMP NULL DEFAULT NULL,
--   `updated_at` TIMESTAMP NULL DEFAULT NULL,
--   PRIMARY KEY (`id`))
-- ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mensakas`.`consumers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mensakas`.`consumers` (
  `consumers_id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `mail` VARCHAR(45) NOT NULL,
  `phone` INT(9) NOT NULL,
  `address` VARCHAR(45) NOT NULL,
  `city` VARCHAR(45) NOT NULL,
  `target` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`consumers_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mensakas`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mensakas`.`product` (
  `product_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `status` TINYINT NOT NULL,
  `price` DECIMAL(5,2) NOT NULL,
  `description` VARCHAR(300) NULL,
  `business_business_id` INT NOT NULL,
  PRIMARY KEY (`product_id`, `business_business_id`),
  INDEX `fk_product_business1_idx` (`business_business_id` ASC) VISIBLE,
  CONSTRAINT `fk_product_business1`
    FOREIGN KEY (`business_business_id`)
    REFERENCES `mensakas`.`business` (`business_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mensakas`.`pack`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mensakas`.`pack` (
  `pack_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `price` DECIMAL(5,2) NOT NULL,
  `status` TINYINT NOT NULL,
  `description` VARCHAR(300) NULL,
  `business_business_id` INT NOT NULL,
  PRIMARY KEY (`pack_id`, `business_business_id`),
  INDEX `fk_pack_business1_idx` (`business_business_id` ASC) VISIBLE,
  CONSTRAINT `fk_pack_business1`
    FOREIGN KEY (`business_business_id`)
    REFERENCES `mensakas`.`business` (`business_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mensakas`.`extra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mensakas`.`extra` (
  `extra_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `price` DECIMAL(5) NOT NULL,
  PRIMARY KEY (`extra_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mensakas`.`business_category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mensakas`.`business_category` (
  `business_category_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `business_id` INT NOT NULL,
  INDEX `fk_business_category_user_business1_idx` (`business_id` ASC) VISIBLE,
  PRIMARY KEY (`business_category_id`),
  CONSTRAINT `fk_business_category_user_business1`
    FOREIGN KEY (`business_id`)
    REFERENCES `mensakas`.`business` (`business_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mensakas`.`product_category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mensakas`.`product_category` (
  `product_category_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`product_category_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mensakas`.`idioms`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mensakas`.`idioms` (
  `castellano` TEXT NULL,
  `catalan` TEXT NULL,
  `ingles` TEXT NULL,
  `product_id` INT NOT NULL,
  `business_id` INT NOT NULL,
  INDEX `fk_idioms_product1_idx` (`product_id` ASC, `business_id` ASC) VISIBLE,
  CONSTRAINT `fk_idioms_product1`
    FOREIGN KEY (`product_id` , `business_id`)
    REFERENCES `mensakas`.`product` (`product_id` , `business_business_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mensakas`.`order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mensakas`.`order` (
  `order_id` INT NOT NULL AUTO_INCREMENT,
  `date_created` DATE NOT NULL,
  `date_update` DATE NOT NULL,
  `status` TINYINT NOT NULL,
  `price` DECIMAL(5,2) NOT NULL,
  `description` VARCHAR(300) NULL,
  `pack_pack_id` INT NOT NULL,
  `product_id` INT NOT NULL,
  `consumers_id` INT NOT NULL,
  `json` JASON NULL,
  PRIMARY KEY (`order_id`),
  INDEX `fk_order_pack1_idx` (`pack_pack_id` ASC) VISIBLE,
  INDEX `fk_order_product1_idx` (`product_id` ASC) VISIBLE,
  INDEX `fk_order_user_consumers1_idx` (`consumers_id` ASC) VISIBLE,
  CONSTRAINT `fk_order_pack1`
    FOREIGN KEY (`pack_pack_id`)
    REFERENCES `mensakas`.`pack` (`pack_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_order_product1`
    FOREIGN KEY (`product_id`)
    REFERENCES `mensakas`.`product` (`product_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_order_user_consumers1`
    FOREIGN KEY (`consumers_id`)
    REFERENCES `mensakas`.`consumers` (`consumers_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mensakas`.`payment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mensakas`.`payment` (
  `payment_id` INT NOT NULL AUTO_INCREMENT,
  `token` VARCHAR(45) NOT NULL,
  `status` TINYINT NOT NULL,
  `created_date` DATE NOT NULL,
  `order_id` INT NOT NULL,
  `consumers_id` INT NOT NULL,
  PRIMARY KEY (`payment_id`, `order_id`, `consumers_id`),
  INDEX `fk_payment_order1_idx` (`order_id` ASC) VISIBLE,
  CONSTRAINT `fk_payment_order1`
    FOREIGN KEY (`order_id`)
    REFERENCES `mensakas`.`order` (`order_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mensakas`.`invoice`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mensakas`.`invoice` (
  `invoice_id` INT NOT NULL,
  `order_order_id` INT NOT NULL,
  PRIMARY KEY (`invoice_id`, `order_order_id`),
  INDEX `fk_invoice_order1_idx` (`order_order_id` ASC) VISIBLE,
  CONSTRAINT `fk_invoice_order1`
    FOREIGN KEY (`order_order_id`)
    REFERENCES `mensakas`.`order` (`order_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mensakas`.`location_mensaka`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mensakas`.`location_mensaka` (
  `location_mensaka_id` INT NOT NULL AUTO_INCREMENT,
  `lat` DECIMAL(11,8) NOT NULL,
  `lon` DECIMAL(11,8) NOT NULL,
  `mensakas_id` INT NOT NULL,
  PRIMARY KEY (`location_mensaka_id`, `mensakas_id`),
  INDEX `fk_location_mensaka_user_mensakas1_idx` (`mensakas_id` ASC) VISIBLE,
  CONSTRAINT `fk_location_mensaka_user_mensakas1`
    FOREIGN KEY (`mensakas_id`)
    REFERENCES `mensakas`.`mensaka` (`mensakas_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mensakas`.`business_timetable`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mensakas`.`business_timetable` (
  `business_id` INT NOT NULL,
  `day` INT(1) NOT NULL,
  `open` TIME NOT NULL,
  `close` TIME NOT NULL,
  INDEX `fk_business_timetable_user_business1_idx` (`business_id` ASC) VISIBLE,
  CONSTRAINT `fk_business_timetable_user_business1`
    FOREIGN KEY (`business_id`)
    REFERENCES `mensakas`.`business` (`business_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mensakas`.`extra_has_product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mensakas`.`extra_has_product` (
  `extra_id` INT NOT NULL,
  `product_id` INT NOT NULL,
  PRIMARY KEY (`extra_id`, `product_id`),
  INDEX `fk_extra_has_product_product1_idx` (`product_id` ASC) VISIBLE,
  INDEX `fk_extra_has_product_extra1_idx` (`extra_id` ASC) VISIBLE,
  CONSTRAINT `fk_extra_has_product_extra1`
    FOREIGN KEY (`extra_id`)
    REFERENCES `mensakas`.`extra` (`extra_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_extra_has_product_product1`
    FOREIGN KEY (`product_id`)
    REFERENCES `mensakas`.`product` (`product_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mensakas`.`product_has_product_category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mensakas`.`product_has_product_category` (
  `product_id` INT NOT NULL,
  `product_category_id` INT NOT NULL,
  PRIMARY KEY (`product_id`, `product_category_id`),
  INDEX `fk_product_has_product_category_product_category1_idx` (`product_category_id` ASC) VISIBLE,
  INDEX `fk_product_has_product_category_product1_idx` (`product_id` ASC) VISIBLE,
  CONSTRAINT `fk_product_has_product_category_product1`
    FOREIGN KEY (`product_id`)
    REFERENCES `mensakas`.`product` (`product_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_product_has_product_category_product_category1`
    FOREIGN KEY (`product_category_id`)
    REFERENCES `mensakas`.`product_category` (`product_category_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mensakas`.`order_message`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mensakas`.`order_message` (
  `data` DATE NOT NULL,
  `text` TEXT NULL,
  `order_id` INT NOT NULL,
  `mensakas_id` INT NOT NULL,
  `business_business_id` INT NOT NULL,
  PRIMARY KEY (`order_id`, `mensakas_id`, `business_business_id`),
  INDEX `fk_order_message_mensaka1_idx` (`mensakas_id` ASC) VISIBLE,
  INDEX `fk_order_message_business1_idx` (`business_business_id` ASC) VISIBLE,
  CONSTRAINT `fk_order_message_order1`
    FOREIGN KEY (`order_id`)
    REFERENCES `mensakas`.`order` (`order_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_order_message_mensaka1`
    FOREIGN KEY (`mensakas_id`)
    REFERENCES `mensakas`.`mensaka` (`mensakas_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_order_message_business1`
    FOREIGN KEY (`business_business_id`)
    REFERENCES `mensakas`.`business` (`business_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mensakas`.`order_deliver`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mensakas`.`order_deliver` (
  `status` TINYINT NOT NULL,
  `order_order_id` INT NOT NULL,
  `mensaka_mensakas_id` INT NOT NULL,
  INDEX `fk_order_deliver_order1_idx` (`order_order_id` ASC) VISIBLE,
  INDEX `fk_order_deliver_mensaka1_idx` (`mensaka_mensakas_id` ASC) VISIBLE,
  CONSTRAINT `fk_order_deliver_order1`
    FOREIGN KEY (`order_order_id`)
    REFERENCES `mensakas`.`order` (`order_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_order_deliver_mensaka1`
    FOREIGN KEY (`mensaka_mensakas_id`)
    REFERENCES `mensakas`.`mensaka` (`mensakas_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
